<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-26T06:33:03 GMT-11:00" name="Suite" finished-at="2021-02-26T06:34:11 GMT-11:00" duration-ms="67690">
    <groups>
    </groups>
    <test started-at="2021-02-26T06:33:03 GMT-11:00" name="Test" finished-at="2021-02-26T06:34:11 GMT-11:00" duration-ms="67690">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="openApplication()[pri:0, instance:tests.LoginTest@550ee7e5]" started-at="2021-02-26T06:34:01 GMT-11:00" name="openApplication" finished-at="2021-02-26T06:34:06 GMT-11:00" duration-ms="5139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="login()[pri:0, instance:tests.LoginTest@550ee7e5]" started-at="2021-02-26T06:34:06 GMT-11:00" name="login" finished-at="2021-02-26T06:34:10 GMT-11:00" duration-ms="4566" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closure()[pri:0, instance:tests.LoginTest@550ee7e5]" started-at="2021-02-26T06:34:10 GMT-11:00" name="closure" finished-at="2021-02-26T06:34:11 GMT-11:00" duration-ms="239" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
      </class> <!-- tests.LoginTest -->
      <class name="tests.login_with_dd">
        <test-method is-config="true" signature="openApplication()[pri:0, instance:tests.login_with_dd@15bbf42f]" started-at="2021-02-26T06:33:21 GMT-11:00" name="openApplication" finished-at="2021-02-26T06:33:27 GMT-11:00" duration-ms="5673" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="login(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:tests.login_with_dd@15bbf42f]" started-at="2021-02-26T06:33:27 GMT-11:00" name="login" data-provider="getLoginData" finished-at="2021-02-26T06:33:41 GMT-11:00" duration-ms="14127" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Success]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Success] but found [Failure]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Success] but found [Failure]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at tests.login_with_dd.login(login_with_dd.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closure()[pri:0, instance:tests.login_with_dd@15bbf42f]" started-at="2021-02-26T06:33:41 GMT-11:00" name="closure" finished-at="2021-02-26T06:33:41 GMT-11:00" duration-ms="219" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
        <test-method is-config="true" signature="openApplication()[pri:0, instance:tests.login_with_dd@15bbf42f]" started-at="2021-02-26T06:33:41 GMT-11:00" name="openApplication" finished-at="2021-02-26T06:33:46 GMT-11:00" duration-ms="5322" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="login(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:tests.login_with_dd@15bbf42f]" started-at="2021-02-26T06:33:46 GMT-11:00" name="login" data-provider="getLoginData" finished-at="2021-02-26T06:34:00 GMT-11:00" duration-ms="13987" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[dummy@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Failure]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closure()[pri:0, instance:tests.login_with_dd@15bbf42f]" started-at="2021-02-26T06:34:00 GMT-11:00" name="closure" finished-at="2021-02-26T06:34:01 GMT-11:00" duration-ms="231" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
      </class> <!-- tests.login_with_dd -->
      <class name="tests.suspend_func">
        <test-method is-config="true" signature="openApplication()[pri:0, instance:tests.suspend_func@2dde1bff]" started-at="2021-02-26T06:33:03 GMT-11:00" name="openApplication" finished-at="2021-02-26T06:33:15 GMT-11:00" duration-ms="11589" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="suspend()[pri:0, instance:tests.suspend_func@2dde1bff]" started-at="2021-02-26T06:33:15 GMT-11:00" name="suspend" finished-at="2021-02-26T06:33:21 GMT-11:00" duration-ms="6479" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suspend -->
      </class> <!-- tests.suspend_func -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
